version: 2.1

jobs:
  checkout_code:
    working_directory: ~/repo
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build_and_push:
    working_directory: ~/repo
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/repo.tar
            - /tmp/trivy/
      - run: set +o pipefail; docker load -i /caches/repo.tar | true
      - run: docker build --cache-from=myapp -t myapp .
      - run: mkdir -p /caches && docker save -o /caches/repo.tar myapp
      - run:
          name: Install Aquasecurity Trivy
          command: |
            apk add --update-cache --upgrade curl && \
            curl -sfL \
            https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin
      - run:
          name: Download JUnit formatter
          command: |
            curl -sfL -o junit.tpl \
            https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl
      - run: mkdir -p ~/tests/
      - run: mkdir -p /tmp/trivy/
      - run:
          name: Scan image with Trivy
          # command: |
          #   trivy image --exit-code 0 --no-progress \
          #   --format template --template "@junit.tpl" \
          #   -o ~/tests/trivy-scan.xml myapp
          command: |
            trivy image --exit-code 0 --no-progress \
            --ignore-unfixed --severity CRITICAL,HIGH,MEDIUM \
            --format template --template "@junit.tpl" \
            --cache-dir /tmp/trivy/ \
            -o ~/tests/trivy-scan.xml myapp
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/repo.tar
            - /tmp/trivy/
      - store_test_results:
          path: ~/tests
      - run:
          name: Emulate pushing
          # docker login here
          # docker push here
          command: |
            set +o pipefail; docker images

workflows:
  version: 2
  my_workflow:
    jobs:
      - checkout_code
      - build_and_push:
          requires:
            - checkout_code
