version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

executors:
  trivy:
    docker:
      - image: aquasec/trivy:0.41.0

jobs:
  build-and-push:
    executor: aws-cli/default
    steps:
      #
      # put steps to buid and push image to ECR here
      #
      # placeholder
      - run:
          name: Build and push image to ECR
          command: |
            echo "Build and push image to ECR"

  scan-image:
    executor: trivy
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install AWS CLI, bash, and jq
          command: |
            apk add --no-cache bash aws-cli jq
      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id $TST_AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $TST_AWS_SECRET_ACCESS_KEY
            aws configure set default.region $TST_AWS_DEFAULT_REGION
      - run:
          name: Get latest image tag and scan image
          command: |
            TAG=$(aws ecr describe-images --repository-name $REPO_NAME --output json | jq -r '.imageDetails |= sort_by(.imagePushedAt) | .imageDetails[].imageTags[-1]' | tail -1)\ &&
            export TAG && \
            trivy image --ignore-unfixed --format table --exit-code 1 --no-progress --vuln-type os,library --severity CRITICAL,HIGH,MEDIUM $ECR_URL/$REPO_NAME:$TAG

workflows:
  version: 2
  build-deploy-and-scan:
    jobs:
      - build-and-push
      - scan-image:
          requires:
            - build-and-push
